# Hand wrench 手臂末端力矩
hand_wrench:
  case1_for_changchun_yiqi_box: # 需要唯一标识
    default: true # VR App端未下发命令时，使用的默认配置
    description: "默认配置1: 一汽绿色箱子"
    itemMass: 5.0 # kg 物品质量
    lforceX: 0.0  
    lforceY: 15   # N  正数表示夹紧方向，负数表示松开方向
    lforceZ: -5.0  # N  正数表示向上
  case2_for_hefei_box:
    description: "默认配置2: 合肥灰色箱子"
    itemMass: 5.0 # kg 物品质量
    lforceX: 0.0  
    lforceY: 15   # N  正数表示夹紧方向，负数表示松开方向
    lforceZ: -5.0  # N  正数表示向上
  case3:
    description: "默认配置3"
    itemMass: 5.0 # kg 物品质量
    lforceX: 0.0  
    lforceY: 15   # N  正数表示夹紧方向，负数表示松开方向
    lforceZ: -5.0  # N  正数表示向上